### ISSUE TITLE
not able to install mkl libraries.

### ISSUE THREAD

**Issue by harveenchadha** [udacity/nd320-c1-emr-data-starter#1]
Hi,

Can you please check  when i try to install libraries from requirement.txt:

ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.15 (from -r requirements.txt (line 69)) (from versions: none)
ERROR: No matching distribution found for mkl-fft==1.0.15 (from -r requirements.txt (line 69))

**Comment by md14kpi** [comment]
Hi Harveen,
Thanks for pointing out this issue and sorry for the delay in responding. It's been a crazy month.  I overlooked updating this part and the requirements.txt should be updated and you should be able to import the project notebook libraries(just tested now). However, please tell me if you have any further issues. 
Thanks,
Michael

**Comment by harveenchadha** [comment]
Thanks for the update Michael.

I have some more issue executing the jupyter notebook. Should I open issues one by one? Or list them here with screenshots?

Thanks,
Harveen

**Comment by md14kpi** [comment]
Hi Harveen, 
Weird I didn't get the notification. I just happen to see now. If possible, put them all together here. I am hoping that it's one particular issue underlying them all but we can break them out if they are separate. Thanks!
